language: android

android:
  components:
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

notifications:
  email: false

script:
  - jdk_switcher use oraclejdk8
  - export GRADLE_OPTS="-Xmx768m -Xms256m -Xss1m"
  - ./gradlew clean build connectedCheck

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
